name: Check agent
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check
        run: |
          gradle -si check
