name: Build & publish artifacts
on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Check and publish to Maven repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: |
          gradle publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
