name: Build & publish artifacts
on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Check and publish to Maven repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Gradle Cache
        id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle Build Cache
        id: cache-build
        uses: actions/cache@v1
        with:
          path: ./build-cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Check
        run: gradle build
      - name: Publish
        run: |
          gradle publish
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
